import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "bg-base": "var(--bg-base)",
        "bg-surface": "var(--bg-surface)",
        "bg-elevated": "var(--bg-elevated)",
        "bg-overlay": "var(--bg-overlay)",
        "bg-subtle": "var(--bg-subtle)",
        "blue-950": "var(--blue-950)",
        "blue-900": "var(--blue-900)",
        "blue-800": "var(--blue-800)",
        "blue-700": "var(--blue-700)",
        "blue-600": "var(--blue-600)",
        "blue-500": "var(--blue-500)",
        "blue-400": "var(--blue-400)",
        "blue-300": "var(--blue-300)",
        "blue-200": "var(--blue-200)",
        "blue-100": "var(--blue-100)",
        "cyan-500": "var(--cyan-500)",
        "cyan-400": "var(--cyan-400)",
        "cyan-300": "var(--cyan-300)",
        "cyan-200": "var(--cyan-200)",
        "green-500": "var(--green-500)",
        "green-400": "var(--green-400)",
        "amber-500": "var(--amber-500)",
        "amber-400": "var(--amber-400)",
        "red-500": "var(--red-500)",
        "red-400": "var(--red-400)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
        "text-accent": "var(--text-accent)",
      },
      boxShadow: {
        "glow-blue": "var(--shadow-glow-blue)",
        "glow-blue-intense": "var(--shadow-glow-blue-intense)",
        "card": "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        "modal": "var(--shadow-modal)",
        "inner": "var(--shadow-inner)",
      },
      borderRadius: {
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        full: "9999px",
      },
      spacing: {
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-5": "20px",
        "space-6": "24px",
        "space-8": "32px",
        "space-10": "40px",
        "space-12": "48px",
        "space-16": "64px",
        "space-20": "80px",
        "space-24": "96px",
      },
      fontFamily: {
        display: ["Syne", "sans-serif"],
        body: ["DM Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
